flowchart TD
title["**example-test-suites/setUserAsAdmin.spec.ts**"]
N0(["setUserAsAdmin"])
N1["when authenticated user is not admin"]
N0 --> N1
N2(["throws exception"])
N1 --> N2
N3["when authenticated user is admin"]
N0 --> N3
N4["when email matches no user in database"]
N3 --> N4
N5["when user not found in ERP"]
N4 --> N5
N6(["throws exception"])
N5 --> N6
N7["when user found in ERP"]
N4 --> N7
N8(["creates user from ERP, sets as admin in database"])
N7 --> N8
N9["when email matches user in database"]
N3 --> N9
N10["when user already has admin role"]
N9 --> N10
N11(["throws exception"])
N10 --> N11
N12["when user has no admin role"]
N9 --> N12
N13(["sets as admin in database, does not call ERP"])
N12 --> N13