import fsExtra from "fs-extra";
import path from "path";
import { runCli } from "./utils";

const ROOT_DIR = path.resolve(__dirname, "../../..");

const SPEC_FILES_DIRECTORY = path.resolve(ROOT_DIR, ".tmp.cli.src");
const SPEC_FILE_NAME = "cli-example.spec.ts";
const SPEC_FILE_PATH = path.join(SPEC_FILES_DIRECTORY, SPEC_FILE_NAME);

const SPEC_FILE_CONTENT = `describe("some test suite", () => {
  it("implements behavior", () => {});
});`;

const SPEC_GLOB = `${path.relative(
  ROOT_DIR,
  SPEC_FILES_DIRECTORY
)}/**/*.spec.ts`;

const SINGLE_OUTPUT_FILE = path.resolve(ROOT_DIR, ".tmp.cli-output.md");

async function cleanUpLocalFileSystem() {
  await fsExtra.remove(SPEC_FILES_DIRECTORY);
  await fsExtra.remove(SINGLE_OUTPUT_FILE);
}

describe("speccharts CLI (integration tests)", () => {
  beforeEach(async () => {
    await cleanUpLocalFileSystem();
    await fsExtra.outputFile(SPEC_FILE_PATH, SPEC_FILE_CONTENT);
  });

  afterAll(async () => {
    await cleanUpLocalFileSystem();
  });

  describe("when passed `--single-output-file`", () => {
    it("writes a single Markdown file with all charts", async () => {
      const { stdout, stderr, exitCode } = await runCli([
        "--input-file-patterns",
        SPEC_GLOB,
        "--single-output-file",
        SINGLE_OUTPUT_FILE,
      ]);

      expect(exitCode).toBe(0);
      expect(stderr).toBe("");

      expect(stdout).toContain("Input file patterns:");
      expect(stdout).toContain("single Markdown file with all charts");

      expect(await fsExtra.pathExists(`${SPEC_FILE_PATH}.mmd`)).toBe(false);
      expect(await fsExtra.pathExists(SINGLE_OUTPUT_FILE)).toBe(true);

      const fileContent = await fsExtra.readFile(SINGLE_OUTPUT_FILE, "utf8");
      expect(fileContent).toContain("# speccharts");
      expect(fileContent).toContain("```mermaid");
      expect(fileContent).toContain("implements behavior");
    });
  });

  describe("when passed `--multiple-output-files`", () => {
    it("writes Mermaid files next to spec files and prints command header", async () => {
      const { stdout, stderr, exitCode } = await runCli([
        "--input-file-patterns",
        SPEC_GLOB,
        "--multiple-output-files",
      ]);

      expect(exitCode).toBe(0);
      expect(stderr).toBe("");

      expect(stdout).toContain("Input file patterns:");
      expect(stdout).toContain("Wrote 1 chart file");

      const chartFilePath = `${SPEC_FILE_PATH}.mmd`;
      expect(await fsExtra.pathExists(chartFilePath)).toBe(true);
      expect(await fsExtra.pathExists(SINGLE_OUTPUT_FILE)).toBe(false);

      const chartContent = await fsExtra.readFile(chartFilePath, "utf8");
      expect(chartContent).toContain("implements behavior");
    });
  });

  describe("when passed both `--single-output-file` and `--multiple-output-files`", () => {
    it("exits with an error without writing files", async () => {
      const { stdout, stderr, exitCode } = await runCli([
        "--input-file-patterns",
        SPEC_GLOB,
        "--single-output-file",
        SINGLE_OUTPUT_FILE,
        "--multiple-output-files",
      ]);

      expect(exitCode).toBe(1);
      expect(stdout).toBe("");
      expect(stderr).toContain(
        "❌ Error: Cannot specify both --single-output-file and --multiple-output-files."
      );

      expect(await fsExtra.pathExists(`${SPEC_FILE_PATH}.mmd`)).toBe(false);
      expect(await fsExtra.pathExists(SINGLE_OUTPUT_FILE)).toBe(false);
    });
  });

  describe("when passed no output flag", () => {
    it("prints a single Markdown document to stdout", async () => {
      const { stdout, stderr, exitCode } = await runCli([
        "--input-file-patterns",
        SPEC_GLOB,
      ]);

      expect(exitCode).toBe(0);
      expect(stderr).toBe("");

      const chartPath = `${SPEC_FILE_PATH}.mmd`;
      expect(await fsExtra.pathExists(chartPath)).toBe(false);
      expect(await fsExtra.pathExists(SINGLE_OUTPUT_FILE)).toBe(false);

      expect(stdout).toContain("```mermaid");
      expect(stdout).toContain("implements behavior");
      expect(stdout).toContain("Generated by speccharts");
    });
  });
});
