import { SpecChart } from "../types";

export function gatherChartsInMarkdown(charts: SpecChart[]): string {
  return `# Spec charts

<!-- Generated by speccharts -->
  
${charts
  .map(({ chart }) => `\`\`\`mermaid\n${chart}\n\`\`\``)
  .join("\n\n---\n\n")}`;
}
