import { gatherChartsInMarkdown } from "./gatherChartsInMarkdown";

describe("gatherChartsInMarkdown", () => {
  it("gathers charts in Markdown", () => {
    const charts = [
      {
        testFile: { path: "testFile1.ts", content: "testFile1" },
        chart: "flowchart TD\nfirst chart…",
      },
      {
        testFile: { path: "testFile2.ts", content: "testFile2" },
        chart: "flowchart TD\nsecond chart…",
      },
    ];
    const result = gatherChartsInMarkdown(charts);
    expect(result).toEqual(`# Spec charts

<!-- Generated by speccharts -->
  
\`\`\`mermaid
flowchart TD
first chart…
\`\`\`

---

\`\`\`mermaid
flowchart TD
second chart…
\`\`\``);
  });
});
