flowchart TD
title["**src/getEBXUser.spec.ts**"]
N0(["getEBXUser"])
N1{"is EBX client enabled?"}
N0 --> N1
N2(["returns \`null\`"])
N1 -- no --> N2
N3{"is EBX people store empty?"}
N4(["returns \`null\`"])
N3 -- yes --> N4
N5{"is \`warnIfNotFound\` enabled (default behavior)?"}
N6(["logs warning"])
N5 -- yes --> N6
N7(["does not log warning"])
N5 -- no --> N7
N3 -- yes --> N5
N8{"is user found?"}
N9(["returns \`null\`"])
N8 -- no --> N9
N10{"is \`warnIfNotFound\` enabled (default behavior)?"}
N11(["logs warning"])
N10 -- yes --> N11
N12(["does not log warning"])
N10 -- no --> N12
N8 -- no --> N10
N13(["returns EBX user, with properties mapped to ThirdPartyUser"])
N8 -- yes --> N13
N3 -- no --> N8
N1 -- yes --> N3
