import packageJson from "../../package.json";

export const GENERATED_BY_SPECCHARTS_IDENTIFIER = "✴ Generated by speccharts";

export const GENERATED_BY_SPECCHARTS_LABEL = `${GENERATED_BY_SPECCHARTS_IDENTIFIER} v${packageJson.version} ✴ https://github.com/arnaudrenaud/speccharts`;
